In [1]:
import numpy as np
import cv2

from keras.models import load_model
from keras.preprocessing import image
from PIL import Image

In [2]:
model = load_model("FaceMaskModel.h5")
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_alt2.xml') 

In [3]:
cap = cv2.VideoCapture(0)
cap.set(3,640)
cap.set(4,480)

True

In [4]:
while True:
    success, temp = cap.read()
    img = cv2.flip(temp, 1)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(60, 60), flags=cv2.CASCADE_SCALE_IMAGE)
    for (x, y, w, h) in faces:  
        faceFrame = img[y: y + h, x: x + w]
        faceFrame = cv2.cvtColor(faceFrame, cv2.COLOR_BGR2RGB)
        faceFrame = cv2.resize(faceFrame, (128, 128))
        faceFrame = image.img_to_array(faceFrame)
        faceFrame = np.expand_dims(faceFrame, axis=0)
        faceFrame = faceFrame/255.0
        predictions = model.predict(faceFrame)
        print(predictions[0])
        (incorrectMask, withMask, withoutMask) = predictions[0]
        if incorrectMask > withMask:
            if incorrectMask > withoutMask:
                label = "WEAR MASK PROPERLY!"
            else:
                label = "No Mask Detected"
        else:
            if withMask > withoutMask:
                label = "Well Masked"
            else:
                label = "No Mask Detected"
        if label == "Well Masked":
            color = (0, 255, 0)
        elif label=="No Mask Detected":
            color = (0, 0, 255)
        else:
            color = (255, 140, 0)
        label = "{}: {:.2f}%".format(label, max(withMask, withoutMask) * 100)
        cv2.putText(img, label, (x, y- 10), cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 2)
        cv2.rectangle(img, (x, y), (x + w, y + h),color, 2)
    cv2.imshow("Press 'x' to Exit!", img)
    if cv2.waitKey(1) & 0xFF ==ord('x'):
        break
cap.release()
cv2.destroyAllWindows()

[1.04058194e-13 6.39372900e-07 9.99999404e-01]
[1.6759599e-14 4.1845217e-07 9.9999952e-01]
[1.03903756e-13 1.96285350e-06 9.99998093e-01]
[6.5078075e-13 7.2063840e-06 9.9999285e-01]
[2.7271859e-12 1.7624227e-05 9.9998236e-01]
[2.1664434e-13 2.6605753e-06 9.9999738e-01]
[5.7333552e-12 2.1373611e-05 9.9997866e-01]
[4.1429757e-14 1.5278939e-06 9.9999845e-01]
[8.8244557e-14 1.9716708e-06 9.9999797e-01]
[1.8076022e-14 2.6637895e-07 9.9999976e-01]
[7.863066e-12 8.188408e-06 9.999918e-01]
[1.5964763e-13 4.0596402e-07 9.9999964e-01]
[3.1042079e-16 1.0231245e-08 1.0000000e+00]
[5.2349424e-18 4.5918176e-09 1.0000000e+00]
[0. 1. 0.]
[3.6222270e-13 2.2112301e-06 9.9999774e-01]
[1.4854659e-16 1.7259811e-07 9.9999988e-01]
[1.1507371e-17 5.3681564e-08 1.0000000e+00]
[4.5719236e-18 3.4169212e-09 1.0000000e+00]
[1.9577340e-14 6.7265006e-08 9.9999988e-01]
[1.6072619e-17 1.4977797e-08 1.0000000e+00]
[1.0125748e-16 8.3074321e-09 1.0000000e+00]
[2.5293897e-16 4.3663785e-08 1.0000000e+00]
[2.2019990e-19 1.7